### ISSUE TITLE
Use react-markdown

### ISSUE THREAD

**Issue by ben-z** [WATonomous/status#51]
Writing raw HTML Is painful. Have content automatically convert from markdown: https://github.com/remarkjs/react-markdown

**Comment by ben-z** [comment]
Also react-code-block has security vulnerabilities. (See dependably alerts)

**Comment by jimmyygit** [comment]
what kind of html are we writing? im not sure how we can convert everything to markdown

**Comment by ben-z** [comment]
Everything in [modals](https://github.com/WATonomous/status/blob/acb0dce5bd0745660c2072c4ba72e419ff229518/pages/index.js#L148-L229) basically. Writing instructions in md is much easier than writing `<a ...></a>` everywhere.
