### ISSUE TITLE
[Feature] Add info tool tip

### ISSUE THREAD

**Issue by JodyZ0203** [WATonomous/status#59]
Currently it is not obvious that clicking on the component will have a popup
![16911675740743_ pic](https://user-images.githubusercontent.com/56443135/217141935-fe54cd50-df6a-4621-8e67-4558f313b2ea.jpg)

![16921675740769_ pic](https://user-images.githubusercontent.com/56443135/217141886-e8bdf1aa-21a8-4482-b18b-dfa8827e3871.jpg)

Info tool tip
<img width="554" alt="Screen Shot 2023-02-06 at 10 33 57 PM" src="https://user-images.githubusercontent.com/56443135/217141771-64390481-9d99-492c-8934-e94f1734d6bb.png">

**Comment by ben-z** [comment]
We no longer use popups in the newest version
